### ISSUE TITLE
The TDD That Works for Me does not have "tdd" tag

### ISSUE THREAD

**Issue by rozhok** [yegor256/blog#181]
Please add one for better searchability.

http://www.yegor256.com/2017/03/24/tdd-that-works.html

https://github.com/yegor256/blog/blob/master/_posts/2017/mar/2017-03-24-tdd-that-works.md
does have "testing" tag but does not have "tdd".

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@rozhok fixed: https://github.com/yegor256/blog/commit/242f14b811a7d22f30d33b87dbb5d3ffaed2c0f8  pls close the ticket

**Comment by rozhok** [comment]
Thanks!

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT ${buildNumber} 2017-08-04T07:36:32
java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:115)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:89)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:103)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
	at com.zerocracy.farm.reactive.FlushAction.process(FlushAction.java:85)
	at com.zerocracy.farm.reactive.FlushAction.exec(FlushAction.java:67)
	at com.zerocracy.farm.reactive.FlushAction.exec(FlushAction.java:35)
	at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.func.RunnableOf.run(RunnableOf.java:89)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:197)
	at com.zerocracy.farm.reactive.RunnableWithTrigger.run(RunnableWithTrigger.java:52)
	at java....
```
