### ISSUE TITLE
Readme sample finish with error

### ISSUE THREAD

**Issue by FrediKats** [yegor256/blog#647]
Disclaimer:  I'm not expert in docker or ruby, just trying to run sample from readme.
Repository contains this code sample:

```
docker run -it --rm \
  -v "$(readlink -f /code/blog):/b" \
  -p 4000:4000 --host=0.0.0.0 \
  yegor256/blog-image \
  'cd /b && bundle update && bundle exec jekyll serve --drafts --future'
```

I was trying to run it on my machine and get two errors.

First error: docker run failed when I tried to pass --host. I fixed it with moving `--host=0.0.0.0` from docker run argument to jekyll serve arg:

```
docker run -it --rm \
  -v "$(readlink -f /code/blog):/b" \
  -p 4000:4000  \
  yegor256/blog-image \
  'cd /b && bundle update && bundle exec jekyll serve --drafts --future --host=0.0.0.0'
```

Second error:

```
Configuration file: /b/_config.yml
/usr/local/rvm/gems/ruby-3.2.2/gems/jekyll-chatgpt-translate-0.0.42/lib/jekyll-chatgpt-translate/ping.rb:32: warning: already initialized constant OpenSSL::SSL::VERIFY_PEER
            Source: /b
       Destination: /b/_site
 Incremental build: disabled. Enable with --incremental
      Generating...

...

File /b/uml/930f06f36724929287c1ee82fd95c77b.svg already exists (8545 bytes)
File /b/uml/c415b43f6d14c18e66db32e9d5d6e8b2.svg already exists (17878 bytes)
/usr/local/rvm/gems/ruby-3.2.2/gems/fastimage-2.2.7/lib/fastimage.rb:393:in `read': Is a directory @ io_fread - /b/images/2020/12/ (Errno::EISDIR)
        from /usr/local/rvm/gems/ruby-3.2.2/gems/fastimage-2.2.7/lib/fastimage.rb:393:in `block in fetch_using_read'
```

I also was trying to run https://github.com/yegor256/bloghacks and did it successfully after fixing one issue: https://github.com/yegor256/bloghacks/pull/21.

**Comment by yegor256** [comment]
@FrediKats try to run it like this and show me the output please (I added `--trace` to see the full stack trace):

```
docker run -it --rm \
  -v "$(readlink -f /code/blog):/b" \
  -p 4000:4000  \
  yegor256/blog-image \
  'cd /b && bundle update && bundle exec jekyll serve --drafts --trace --future --host=0.0.0.0'
```

**Comment by FrediKats** [comment]
@yegor256 this log was collected after adding trace.

Full log:

```
Using /usr/local/rvm/gems/ruby-3.2.2
Using /usr/local/rvm/gems/ruby-3.2.2
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Fetching rake 13.1.0
Installing rake 13.1.0
Fetching minitest 5.20.0
Fetching thread_safe 0.3.6
Fetching base64 0.2.0
Fetching colorize 0.8.1
Fetching faraday-net_http 3.0.2
Fetching multipart-post 2.3.0
Fetching fastimage 2.2.7
Fetching mercenary 0.3.6
Fetching racc 1.7.3
Fetching parallel 1.24.0
Fetching yell 2.2.2
Fetching humanize 2.5.1
Fetching iri 0.7.0
Fetching iso-639 0.3.6
Fetching rexml 3.2.6
Fetching date 3.3.4
Fetching event_stream_parser 1.0.0
Fetching json 2.7.1
Fetching public_suffix 5.0.4
Fetching ast 2.4.2
Installing base64 0.2.0
Installing fastimage 2.2.7
Installing parallel 1.24.0
Installing multipart-post 2.3.0
Installing yell 2.2.2
Installing minitest 5.20.0
Installing colorize 0.8.1
Installing faraday-net_http 3.0.2
Fetching redcarpet 3.6.0
Installing iso-639 0.3.6
Fetching tiktoken_ruby 0.0.6 (x86_64-linux)
Installing racc 1.7.3 with native extensions
Installing ast 2.4.2
Installing iri 0.7.0
Installing mercenary 0.3.6
Installing json 2.7.1 with native extensions
Installing date 3.3.4 with native extensions
Installing event_stream_parser 1.0.0
Fetching jekyll-paginate 1.1.0
Installing rexml 3.2.6
Installing public_suffix 5.0.4
Installing humanize 2.5.1
Installing redcarpet 3.6.0 with native extensions
Installing thread_safe 0.3.6
Installing jekyll-paginate 1.1.0
Fetching trollop 2.9.10
Fetching language_server-protocol 3.17.0.3
Fetching mini_mime 1.1.5
Fetching timeout 0.4.1
Fetching nuggets 1.6.1
Fetching pygments.rb 2.4.0
Fetching regexp_parser 2.8.3
Fetching ruby-progressbar 1.13.0
Fetching uuidtools 2.2.0
Fetching ethon 0.16.0
Fetching sassc 2.4.0
Installing timeout 0.4.1
Fetching jekyll-bits 0.15
Installing trollop 2.9.10
Installing mini_mime 1.1.5
Fetching faraday-multipart 1.0.4
Fetching faraday 2.7.12
Installing language_server-protocol 3.17.0.3
Fetching addressable 2.8.6
Installing ruby-progressbar 1.13.0
Installing uuidtools 2.2.0
Installing regexp_parser 2.8.3
Installing nuggets 1.6.1
Installing jekyll-bits 0.15
Installing ethon 0.16.0
Fetching sass-listen 4.0.0
Installing faraday-multipart 1.0.4
Fetching rss 0.3.0
Fetching tzinfo 1.2.11
Installing faraday 2.7.12
Fetching net-protocol 0.2.2
Fetching parser 3.2.2.4
Installing addressable 2.8.6
Installing sassc 2.4.0 with native extensions
Installing sass-listen 4.0.0
Installing rss 0.3.0
Installing net-protocol 0.2.2
Fetching typhoeus 0.8.0
Fetching ruby-openai 6.3.1
Fetching sawyer 0.9.2
Fetching sass 3.7.4
Fetching net-smtp 0.4.0
Installing tzinfo 1.2.11
Installing pygments.rb 2.4.0
Installing typhoeus 0.8.0
Installing sawyer 0.9.2
Installing ruby-openai 6.3.1
Installing net-smtp 0.4.0
Fetching activesupport 5.2.8.1
Fetching octokit 4.25.1
Fetching w3c_validators 1.3.7
Installing sass 3.7.4
Fetching scss_lint 0.60.0
Installing octokit 4.25.1
Fetching jekyll-gist 1.5.0
Installing w3c_validators 1.3.7
Installing jekyll-gist 1.5.0
Installing scss_lint 0.60.0
Installing parser 3.2.2.4
Installing activesupport 5.2.8.1
Installing tiktoken_ruby 0.0.6 (x86_64-linux)
Fetching rubocop-ast 1.30.0
Fetching html-proofer 3.7.5
Installing html-proofer 3.7.5
Installing rubocop-ast 1.30.0
Fetching rubocop 1.59.0
Installing rubocop 1.59.0
Fetching rubocop-capybara 2.19.0
Fetching rubocop-factory_bot 2.24.0
Installing rubocop-factory_bot 2.24.0
Installing rubocop-capybara 2.19.0
Fetching rubocop-rspec 2.25.0
Installing rubocop-rspec 2.25.0
Fetching net-imap 0.4.8
Installing net-imap 0.4.8
Fetching mail 2.8.1
Installing mail 2.8.1
Fetching jekyll-sass-converter 2.2.0
Installing jekyll-sass-converter 2.2.0
Fetching jekyll-plantuml 1.4.1
Fetching jekyll-sitemap 1.4.0
Fetching jekyll-feed 0.17.0
Fetching jekyll-git-hash 0.1.0
Fetching jgd 1.14.0
Fetching jekyll-chatgpt-translate 0.0.42
Fetching jekyll-redirect-from 0.16.0
Fetching jekyll-sass 1.1.0
Installing jekyll-plantuml 1.4.1
Installing jgd 1.14.0
Installing jekyll-git-hash 0.1.0
Installing jekyll-feed 0.17.0
Installing jekyll-redirect-from 0.16.0
Installing jekyll-sitemap 1.4.0
Installing jekyll-chatgpt-translate 0.0.42
Installing jekyll-sass 1.1.0
Bundle updated!
Post-install message from sass:

Ruby Sass has reached end-of-life and should no longer be used.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:
  https://sass-lang.com/blog/posts/7828841

Post-install message from trollop:
!    The 'trollop' gem has been deprecated and has been replaced by 'optimist'.
!    See: https://rubygems.org/gems/optimist
!    And: https://github.com/ManageIQ/optimist
Post-install message from nuggets:

nuggets-1.6.1 [2022-05-18]:

* Ruby 3.1 compatibility.

Configuration file: /b/_config.yml
/usr/local/rvm/gems/ruby-3.2.2/gems/jekyll-chatgpt-translate-0.0.42/lib/jekyll-chatgpt-translate/ping.rb:32: warning: already initialized constant OpenSSL::SSL::VERIFY_PEER
            Source: /b
       Destination: /b/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
WARN: No front image in /2010/03/04/pdd.html
WARN: No front image in /2013/12/29/proto.html
WARN: No front image in /2014/04/06/introduction.html
WARN: No front image in /2014/04/06/movies-for-thanasis.html
WARN: No front image in /2014/04/06/phandom.html
WARN: No front image in /2014/04/09/xembly-intro.html
WARN: No front image in /2014/04/11/jcabi-http-intro.html
WARN: No front image in /2014/04/14/jcabi-dynamo-java-api-of-aws-dynamodb.html
WARN: No front image in /2014/04/15/definition-of-done.html
WARN: No front image in /2014/04/15/github-guidelines.html
WARN: No front image in /2014/04/18/jcabi-http-server-mocking.html
WARN: No front image in /2014/04/20/how-hourly-rate-is-calculated.html
WARN: No front image in /2014/04/21/s3-http-basic-auth.html
WARN: No front image in /2014/04/24/java-xml-parsing-and-traversing.html
WARN: No front image in /2014/04/26/incremental-requirements-with-requs.html
WARN: No front image in /2014/04/27/typical-mistakes-in-java-code.html
WARN: No front image in /2014/04/28/xml-xpath-hamcrest-matchers.html
WARN: No front image in /2014/04/29/w3c-java-validators.html
WARN: No front image in /2014/05/01/dynamodb-local-maven-plugin.html
WARN: No front image in /2014/05/05/oop-alternative-to-utility-classes.html
WARN: No front image in /2014/05/13/why-null-is-bad.html
WARN: No front image in /2014/05/14/object-oriented-github-java-sdk.html
WARN: No front image in /2014/05/18/cloud-autoincrement-counters.html
WARN: No front image in /2014/05/21/mysql-maven-plugin.html
WARN: No front image in /2014/05/23/avoid-java-static-logger.html
WARN: No front image in /2014/05/26/amazon-s3-java-oop-adapter.html
WARN: No front image in /2014/06/01/aop-aspectj-java-method-logging.html
WARN: No front image in /2014/06/09/objects-should-be-immutable.html
WARN: No front image in /2014/06/19/avoid-string-concatenation.html
WARN: No front image in /2014/06/20/limit-method-execution-time.html
WARN: No front image in /2014/06/21/casperjs-with-maven.html
WARN: No front image in /2014/06/24/jekyll-github-deploy.html
WARN: No front image in /2014/06/25/xml-and-xslt-in-browser.html
WARN: No front image in /2014/06/26/sass-in-java-webapp.html
WARN: No front image in /2014/06/29/custom-lexer-in-jekyll.html
WARN: No front image in /2014/07/03/how-to-read-manifest-mf.html
WARN: No front image in /2014/07/20/liquibase-in-maven.html
WARN: No front image in /2014/07/21/read-only-master-branch.html
WARN: No front image in /2014/07/24/rultor-automated-merging.html
WARN: No front image in /2014/07/29/docker-in-rultor.html
WARN: No front image in /2014/07/31/travis-and-rultor.html
WARN: No front image in /2014/08/03/cacheable-java-annotation.html
WARN: No front image in /2014/08/15/retry-java-method-on-exception.html
WARN: No front image in /2014/08/18/fluent-jdbc-decorator.html
WARN: No front image in /2014/08/19/how-to-release-to-maven-central.html
WARN: No front image in /2014/08/22/art-of-software-testing.html
WARN: No front image in /2014/08/25/deploy-to-cloudbees.html
WARN: No front image in /2014/08/26/publish-to-rubygems.html
WARN: No front image in /2014/08/29/docker-non-root.html
WARN: No front image in /2014/09/02/java-ssh-client.html
WARN: No front image in /2014/09/10/anti-patterns-in-oop.html
WARN: No front image in /2014/09/13/deploying-to-heroku.html
WARN: No front image in /2014/09/22/remote-programming-interview.html
WARN: No front image in /2014/09/23/built-in-fake-objects.html
WARN: No front image in /2014/09/24/why-monetary-awards-dont-work.html
WARN: No front image in /2014/10/03/di-containers-are-evil.html
WARN: No front image in /2014/10/05/ten-hosted-continuous-integration-services.html
WARN: No front image in /2014/10/06/software-project-lifecycle.html
WARN: No front image in /2014/10/08/continuous-integration-is-dead.html
WARN: No front image in /2014/10/21/incremental-billing.html
WARN: No front image in /2014/10/23/paired-brackets-notation.html
WARN: No front image in /2014/10/26/hacker-vs-programmer-mentality.html
WARN: No front image in /2014/11/03/empty-line-code-smell.html
WARN: No front image in /2014/11/07/how-immutability-helps.html
WARN: No front image in /2014/11/14/hits-of-code.html
WARN: No front image in /2014/11/20/seven-virtues-of-good-object.html
WARN: No front image in /2015/01/10/windows-appveyor-maven.html
WARN: No front image in /2015/01/21/if-then-throw-else.html
WARN: No front image in /2015/02/02/xsl-transformations-in-java.html
WARN: No front image in /2015/02/05/jcabi-parent-maven-pom.html
WARN: No front image in /2015/03/26/jaxb-vs-xembly.html
WARN: No front image in /2015/03/29/rultor-with-appveyor.html
WARN: No front image in /2015/04/13/tacit-css-framework-for-dummies.html
WARN: No front image in /2015/04/22/favorite-software-books.html
WARN: No front image in /2015/04/30/iterating-adapter.html
WARN: No front image in /2015/05/18/cookie-based-authentication.html
WARN: No front image in /2015/06/08/deadly-sins-software-project.html
WARN: No front image in /2015/06/11/wikipedia-bug-definition.html
WARN: No front image in /2015/06/25/xml-data-xsl-views-takes-framework.html
WARN: No front image in /2015/08/18/multiple-return-statements-in-oop.html
WARN: No front image in /2015/09/07/maven-repository-amazon-s3.html
WARN: No front image in /2015/11/03/chatbot-better-than-ui-for-microservice.html
WARN: No front image in /2016/03/15/wring-dispatcher-github-notifications.html
WARN: No front image in /2016/03/30/jare-instant-free-cdn.html
WARN: No front image in /2016/11/18/software-conferences-to-attend.html
WARN: No front image in /2017/06/13/dynamodb-rack-maven.html
WARN: No front image in /2017/06/22/object-oriented-input-output-in-cactoos.html
WARN: No front image in /2017/06/27/my-environment.html
WARN: No front image in /2017/07/25/my-favorite-websites.html
WARN: No front image in /2017/09/05/rehttp-http-repeater.html
WARN: No front image in /2018/10/30/mailanes.html
WARN: No front image in /2018/11/06/ruby-threads.html
WARN: No front image in /2019/02/03/cloudrepo.html
WARN: No front image in /2019/02/05/zache.html
WARN: No front image in /2019/04/17/nutch-from-java.html
WARN: No front image in /2019/06/26/syncem.html
WARN: No front image in /2023/09/05/style-checker-for-bibtex-files.html
File /b/uml/d892698103dc5669949527a8754c5f26.svg created (3411 bytes)
File /b/uml/52d3d016f2264bbf660a23d5bbe84203.svg created (8680 bytes)
File /b/uml/19b92d0465e2e819ffcf88cf46c6e333.svg created (3963 bytes)
File /b/uml/eee0d1bcdb7b9318e937e99e04e39ff7.svg created (3437 bytes)
File /b/uml/d103661ebf8494340e260442970bf4af.svg created (4564 bytes)
File /b/uml/b5d40b6498ca48f6d2efc8671dd6d1e6.svg created (4463 bytes)
File /b/uml/aecf8b3862f82e6d5d8d27e948d45c83.svg created (5504 bytes)
File /b/uml/653125b6c32d12b7325dba52054c09ca.svg created (3497 bytes)
File /b/uml/cad4de541e1ab10d3d9d751c661fe63f.svg created (3450 bytes)
File /b/uml/45d05ab3bd9a93ad88ec209352b62f60.svg created (3227 bytes)
File /b/uml/b9cc42a8e5ed92f94f4362cfd328fb0d.svg created (13461 bytes)
File /b/uml/930f06f36724929287c1ee82fd95c77b.svg created (8545 bytes)
File /b/uml/c415b43f6d14c18e66db32e9d5d6e8b2.svg created (17878 bytes)
/usr/local/rvm/gems/ruby-3.2.2/gems/fastimage-2.2.7/lib/fastimage.rb:393:in `read': Is a directory @ io_fread - /b/images/2020/12/ (Errno::EISDIR)
        from /usr/local/rvm/gems/ruby-3.2.2/gems/fastimage-2.2.7/lib/fastimage.rb:393:in `block in fetch_using_read'
```

**Comment by yegor256** [comment]
@FrediKats get rid of the `--drafts` flag and it will work

**Comment by FrediKats** [comment]
@yegor256, yes, it works without `--drafts`.

**Comment by yegor256** [comment]
@FrediKats ok, thanks, I will close this one
